image: golang:1.24.2

variables:
  CONFIG_PATH: "$CI_PROJECT_DIR/config/development.gitlab.yml"

workflow:
  # on branch dev and on merge request from dev in main
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || ($CI_PIPELINE_SOURCE == 'merge_request_event' && ( $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" ))

stages:
  - lint
  - test

lint:
  stage: lint
  script:
    - go install golang.org/x/lint/golint@latest
    - export PATH=$PATH:$(go env GOPATH)/bin
    - golint ./...
  allow_failure: true

testing:
  stage: test
  services:
    - name: postgres:15
      alias: postgres
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
    POSTGRES_HOST: postgres
    POSTGRES_PORT: 5432
  before_script:
    # wait for Postgres to be ready
    - apt-get update && apt-get install -y postgresql-client
    - until pg_isready -h $POSTGRES_HOST -p $POSTGRES_PORT; do echo "Waiting for Postgres..."; sleep 1; done
  script:
    - go test ./... -v
