apiVersion: v1
kind: Pod
metadata:
  name: flowreon-user
  labels:
    app: flowreon-user
spec:
  containers:
    - name: user
      image: shanart/flowreon_user:0.9.1
      ports:
        - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: flowreon-user
spec:
  selector:
    app: flowreon-user
  ports:
    - port: 8003
      targetPort: 8003
