name: jajirra


volumes:
  postgres_data:

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASES=postgres
    ports:
      - "5432:5432"
    volumes:
      - ../database/init:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
#
#  migrate:
#    image: migrate/migrate
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#      - DB_HOST=postgres
#      - DB_PORT=5432
#      - DB_NAME=postgres
#    volumes:
#      - ../database/migrations:/migrations
#    entrypoint:
#      [
#        "sh",
#        "-c",
#        "migrate -path /migrations -database postgres://$${DB_USER}:$${DB_PASSWORD}@$${DB_HOST}:$${DB_PORT}/$${DB_NAME}?sslmode=disable -verbose up",
#      ]

# rabbitmq
# redis
# keto