stages:
  - mirror

mirror_to_github:
  stage: mirror
  image: alpine:latest

  only:
    - main

  before_script:
    - apk add --no-cache git openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan github.com >> ~/.ssh/known_hosts

  script:
    - git remote add github git@github.com:shaninalex/lumna-mirror.git || true
    - git fetch --unshallow || true
    - git fetch --all --tags
    - git checkout -B main origin/main
    - git push --force github main:refs/heads/main
