stages:
  - test

variables:
  GO_VERSION: "1.25.6"

test:
  stage: test
  image: golang:${GO_VERSION}
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

  before_script:
    - go version

  script:
    - mkdir -p resources/assets
    - touch resources/assets/placeholder
    - go mod tidy
    - go test -v -coverprofile cover.out ./app/...
