env: testing

serve:
  port: 8000
  embed: false
  setup: true

database:
  type: "sqlite"
  url: "file::memory:?cache=shared"

secret_key: "a-string-secret-at-least-256-bits-long"

email:
  host: "mail.google.com"
  port: 587
  username: "email@example.com"
  password: "password"
