# Application working mode:
# development - additional logging, things can work in mock or local way
# production - more
# testing - most of the things working in mocking way
env: development

serve:
  # port of the server
  port: 8000
  embed: false

database:
  # instead of providing explicit db type we can detect type from connection url
  type: "sqlite" # or "postgres"
  url: "file::memory:?cache=shared"

# for jwt signing and verification
secret_key: "a-string-secret-at-least-256-bits-long"

email:
  host: "mail.google.com"
  port: 587
  username: "email@example.com"
  password: "password"
