auth:
  port: 8000

app:
  dsn: "postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable"
  secret_key: "very-secret-key"

email:
  host: "smtp.gmail.com"
  port: 587
  user: "google user email"
  pass: "app_secret"
  from: "shanin.x@gmail.com"
  tls: true
  smtp: "smtps://test:test@mailslurper:1025/?skip_ssl_verify=true"

kratos:
  url_admin: "http://localhost:4434"
  url_browser: "http://localhost:4433"
