name: "Test"

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: setup Go
        id: build
        uses: actions/setup-go@v3
        with:
          go-version: '^1.25.0'

      - name: tidy
        run: go mod tidy

      - name: Ensure embed directory exists
        run: |
          mkdir -p app/cmd/standalone/web/browser
          touch app/cmd/standalone/web/browser/.keep

      - name: tests
        run: go test -tags noembed ./... -v